//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakery_kr.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingredients()
        {
            this.pastry_ingredient = new HashSet<pastry_ingredient>();
        }
    
        public int id_ingredient { get; set; }
        public string title { get; set; }
        public Nullable<int> quantity { get; set; }
        public string measure_unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pastry_ingredient> pastry_ingredient { get; set; }
    }
}
