//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakery_kr.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bakeryEntities : DbContext
    {
        public bakeryEntities()
            : base("name=bakeryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<ingredients> ingredients { get; set; }
        public virtual DbSet<pastry_ingredient> pastry_ingredient { get; set; }
        public virtual DbSet<pastry_sale> pastry_sale { get; set; }
        public virtual DbSet<Pastrys> Pastrys { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sale> sale { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
