//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakery_kr.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id_Sale { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> Date_Sale { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Id_Pastry { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Pastrys Pastrys { get; set; }
        public virtual User User { get; set; }
    }
}
